name: wiegand
description: Wiegand protocol receiver
groups:
  - misc
code_owners: UncleRus
depends:
  # XXX conditional depends
  - driver
  - log
  - esp_idf_lib_helpers
thread_safe: no
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2021
