name: hdc1000
description: |
  Driver for HDC1000 temperature and humidity sensor
groups:
  - temperature
  - humidity
code_owners:
  - UncleRus
depends:
  - i2cdev
  - log
  - esp_idf_lib_helpers
thread_safe: yes
targets:
  - esp32
  - esp8266
  - esp32s2
  - esp32c3
license: BSD-3
copyrights:
  - name: UncleRus
    year: 2021
