name: framebuffer
description: RGB framebuffer component
groups:
  - common
code_owners: UncleRus
depends:
  - log
  - color
thread_safe: N/A
targets:
  - esp32
  - esp32s2
  - esp32c3
license: MIT
copyrights:
  - name: UncleRus
    year: 2021
